spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: 97d81af458f0357feba8
#            client-secret: ad410610e7a4675c444082773079f56d6b4c8af4

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *